### ISSUE TITLE
requirements.txt typo?

### ISSUE THREAD

**Issue by Blimpyway** [jsonresume/jsonresume-fake#5]
Shouldn't the line 

tengenrnn 

be: 

textgenrnn 

?

**Comment by thomasdavis** [comment]
Correct, fixing now.

**Comment by thomasdavis** [comment]
Thanks @Blimpyway, fixed in -> https://github.com/jsonresume/jsonresume-fake/commit/2c02fb1b97c8b8699c21a10980ccff21145ee41f
